version: '3.2'

services:

  zookeeper:
    image: zookeeper:3.7.0
    ports:
      - "2181:2181"

  broker:
    image: janio/kafka:2.7.0-arm64v8
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  karapace-registry:
    image: janio/karapace:2.0.1
    entrypoint:
      - /bin/bash
      - /opt/karapace/start.sh
      - registry
    ports:
      - "8081:8081"
    environment:
      KARAPACE_REGISTRY_ADVERTISED_HOSTNAME: karapace-registry
      KARAPACE_REGISTRY_BOOTSTRAP_URI: broker:9094
      KARAPACE_REGISTRY_PORT: 8081
      KARAPACE_REGISTRY_HOST: 0.0.0.0
      KARAPACE_REGISTRY_CLIENT_ID: karapace
      KARAPACE_REGISTRY_GROUP_ID: karapace-registry
      KARAPACE_REGISTRY_MASTER_ELIGIBITY: "true"
      KARAPACE_REGISTRY_TOPIC_NAME: _schemas
      KARAPACE_REGISTRY_LOG_LEVEL: WARNING
      KARAPACE_REGISTRY_COMPATIBILITY: FULL

  karapace-rest:
    image: janio/karapace:2.0.1
    entrypoint:
      - /bin/bash
      - /opt/karapace/start.sh
      - rest
    depends_on:
      - kafka
      - karapace-registry
    ports:
      - "8082:8082"
    environment:
      KARAPACE_REST_PORT: 8082
      KARAPACE_REST_HOST: 0.0.0.0
      KARAPACE_REST_ADVERTISED_HOSTNAME: karapace-rest
      KARAPACE_REST_BOOTSTRAP_URI: kafka:29092
      KARAPACE_REST_REGISTRY_HOST: karapace-registry
      KARAPACE_REST_REGISTRY_PORT: 8081
      # Keep in sync with tests/integration/conftest.py::fixture_rest_async,
      # new entries may need to be added to containers/start.sh
      KARAPACE_REST_ADMIN_METADATA_MAX_AGE: 0
      KARAPACE_REST_LOG_LEVEL: WARNING
